### ISSUE TITLE
Postgres for_update skip locking

### ISSUE THREAD

**Issue by fhendrikx** [siracusa/rose#19]
Hi,

Postgres supports for_update locking with either "nowait" or "skip locked", however, adding skip_locked => 1 has no effect. 

Can this be added to the Rose/DB/Pg.pm module?

I believe the following should be sufficient:

diff -w Pg.pm Pg.pm.new
154a155,159
>   if($lock->{'skip_locked'})
>   {
>     $sql .= ' SKIP LOCKED';
>   }

Thank you.

**Comment by siracusa** [comment]
Fixed in Rose::DB 0.779, just uploaded to CPAN.

**Comment by fhendrikx** [comment]
Thank you.
