### ISSUE TITLE
Rose tries to connect to the database on syntax checking

### ISSUE THREAD

**Issue by ulizama** [siracusa/rose#32]
I'm using Perl Navigator on VS Code. The problem is that on scripts or modules that are using Rose::DB::Object, when the syntax checker runs, Rose tries to connect to the database.

I tried to find something on the documentation that would disable the requirement to do a DB connection to check that the table configuration is correct which I think it's what is being executed to avoid this issue.

Is there a way to achieve this? If not, it would be nice to have that feature so that the syntax check doesn't require a live database connection.

**Comment by siracusa** [comment]
Can you show me one of your files that tries to connect to the database when it's syntax-checked? (Or maybe make an example file demonstrating the problem?)

**Comment by ulizama** [comment]
While coming up with a test example I was able to figure out that it's not Rose itself prompting the connection, but a plugin we have to integrate Rose into Dancer which is trying to open the connection on module load which makes it try to connect on syntax check.

I'll close this issue as it's not an issue with Rose.

As a final thought, thank you very much for making these modules, it's by far my favorite ORM and we use it extensively in our company.
