### ISSUE TITLE
parse_interval test failing on postgres

### ISSUE THREAD

**Issue by rewolfe** [siracusa/rose#9]
Lots of errors occur in parse_interval during installation.  Example:

---
#   Failed test 'parse_interval (-0:1:)'
#   at t/pg.t line 313.
#          got: '@ 0'
#     expected: '@ -1 minutes'

#   Failed test 'parse_interval alt check 4'
#   at t/pg.t line 316.

#   Failed test 'parse_interval (2:)'
#   at t/pg.t line 313.
#          got: '@ 0'
#     expected: '@ 120 minutes
---

**Comment by rsindlin** [comment]
Below is the full test output with failures during installation via cpanm.  Pardon me if this is too long; opting for pasting as comment rather than attaching as file, for search engines to pick up should anyone else hit this issue.

```
Fetching http://www.cpan.org/authors/id/J/JS/JSIRACUSA/Rose-DB-Object-0.815.tar.gz
-> OK
Unpacking Rose-DB-Object-0.815.tar.gz
Entering Rose-DB-Object-0.815
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.98)
Configuring Rose-DB-Object-0.815
Running Makefile.PL
Warning: prerequisite Rose::DB 0.763 not found.
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Rose::DB::Object
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Math::BigInt 1.77 ... Yes (1.9993)
Checking if you have Data::Dumper 2.121 ... Yes (2.151)
Checking if you have Scalar::Util 0 ... Yes (1.38)
Checking if you have Rose::DateTime::Util 0.532 ... Yes (0.540)
Checking if you have DBI 1.40 ... Yes (1.634)
Checking if you have Rose::Object 0.854 ... Yes (0.860)
Checking if you have List::MoreUtils 0 ... Yes (0.413)
Checking if you have Time::Clock 1.00 ... Yes (1.03)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.98)
Checking if you have Test::More 0 ... Yes (1.001014)
Checking if you have File::Spec 0 ... Yes (3.47)
Checking if you have File::Path 0 ... Yes (2.09)
Checking if you have Clone 0.29 ... Yes (0.38)
Checking if you have Bit::Vector 0 ... Yes (7.4)
Checking if you have Rose::DB 0.763 ... No
Checking if you have DateTime 0 ... Yes (1.25)
Checking if you have Cwd 0 ... Yes (3.47)
==> Found dependencies: Rose::DB
Searching Rose::DB (0.763) on cpanmetadb ...
--> Working on Rose::DB
Fetching http://www.cpan.org/authors/id/J/JS/JSIRACUSA/Rose-DB-0.777.tar.gz
-> OK
Unpacking Rose-DB-0.777.tar.gz
Entering Rose-DB-0.777
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.98)
Configuring Rose-DB-0.777
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Rose::DB
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have DateTime::Format::Oracle 0 ... Yes (0.06)
Checking if you have Time::Clock 0 ... Yes (1.03)
Checking if you have DateTime::Format::MySQL 0 ... Yes (0.06)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.98)
Checking if you have DateTime::Format::Pg 0.11 ... Yes (0.16011)
Checking if you have Test::More 0 ... Yes (1.001014)
Checking if you have Rose::DateTime::Util 0.532 ... Yes (0.540)
Checking if you have Scalar::Util 0 ... Yes (1.38)
Checking if you have SQL::ReservedWords 0 ... Yes (0.8)
Checking if you have DBI 0 ... Yes (1.634)
Checking if you have Clone::PP 0 ... Yes (1.06)
Checking if you have Bit::Vector::Overload 6.4 ... Yes (7.4)
Checking if you have DateTime::Duration 0 ... Yes (1.25)
Checking if you have Rose::Object 0.854 ... Yes (0.860)
Building and testing Rose-DB-0.777
cp lib/Rose/DB.pm blib/lib/Rose/DB.pm
cp lib/Rose/DB/Oracle.pm blib/lib/Rose/DB/Oracle.pm
cp lib/Rose/DB/Cache/Entry.pm blib/lib/Rose/DB/Cache/Entry.pm
cp lib/Rose/DB/Cache.pm blib/lib/Rose/DB/Cache.pm
cp lib/Rose/DB/Pg.pm blib/lib/Rose/DB/Pg.pm
cp lib/Rose/DB/Generic.pm blib/lib/Rose/DB/Generic.pm
cp lib/Rose/DB/MySQL.pm blib/lib/Rose/DB/MySQL.pm
cp lib/Rose/DB/Registry.pm blib/lib/Rose/DB/Registry.pm
cp lib/Rose/DB/SQLite.pm blib/lib/Rose/DB/SQLite.pm
cp lib/Rose/DB/Constants.pm blib/lib/Rose/DB/Constants.pm
cp lib/Rose/DB/Informix.pm blib/lib/Rose/DB/Informix.pm
cp lib/Rose/DB/Tutorial.pod blib/lib/Rose/DB/Tutorial.pod
cp lib/Rose/DB/Registry/Entry.pm blib/lib/Rose/DB/Registry/Entry.pm
Manifying blib/man3/Rose::DB.3
Manifying blib/man3/Rose::DB::Cache.3
Manifying blib/man3/Rose::DB::Cache::Entry.3
Manifying blib/man3/Rose::DB::Constants.3
Manifying blib/man3/Rose::DB::Generic.3
Manifying blib/man3/Rose::DB::Informix.3
Manifying blib/man3/Rose::DB::MySQL.3
Manifying blib/man3/Rose::DB::Oracle.3
Manifying blib/man3/Rose::DB::Pg.3
Manifying blib/man3/Rose::DB::Registry.3
Manifying blib/man3/Rose::DB::Registry::Entry.3
Manifying blib/man3/Rose::DB::SQLite.3
Manifying blib/man3/Rose::DB::Tutorial.3
PERL_DL_NONLAZY=1 /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t

##
## WARNING: Almost all the tests in this module distribution need to connect
## to a database in order to run.  The tests need full privileges on this
## database: the ability to create and drop tables, insert, update, and delete
## rows, create schemas, sequences, functions, triggers, the works.
##
## By default, the tests will try to connect to the database named "test"
## running on "localhost" using the default superuser username for each
## database type and an empty password.
##
## If you have setup your database in a secure manner, these connection
## attempts will fail, and the tests will be skipped.  If you want to override
## these values, set the following environment variables before running tests.
## (The current values are shown in parentheses.)
##
## PostgreSQL:
##
##     RDBO_PG_DSN        (dbi:Pg:dbname=test;host=localhost)
##     RDBO_PG_USER       (postgres)
##     RDBO_PG_PASS       (<none>)
##
## MySQL:
## 
##     RDBO_MYSQL_DSN     (dbi:mysql:database=test;host=localhost)
##     RDBO_MYSQL_USER    (root)
##     RDBO_MYSQL_PASS    (<none>)
##
## Oracle:
##
##     RDBO_ORACLE_DSN    (dbi:Oracle:dbname=test)
##     RDBO_ORACLE_USER   (<none>)
##     RDBO_ORACLE_PASS   (<none>)
##
## Informix:
##
##     RDBO_INFORMIX_DSN  (dbi:Informix:test@test)
##     RDBO_INFORMIX_USER (<none>)
##     RDBO_INFORMIX_PASS (<none>)
##
## SQLite: To disable the SQLite tests, set this environment varible
##
##     RDBO_NO_SQLITE (<undef>)
##
## Press return to continue (or wait 60 seconds)
t/00-warning.t ............ ok
t/basic.t ................. ok
t/db_cache.t .............. ok
t/fork-informix.t ......... ok
t/fork-mysql.t ............ ok
t/fork-pg.t ............... ok
t/informix.t .............. skipped: Missing DBD::Informix
t/list-tables.t ........... ok
t/mysql.t ................. skipped: Missing DBD::mysql
t/no-registry.t ........... ok
t/oracle.t ................ skipped: Missing DBD::Oracle

#   Failed test 'parse_interval (-0:1:)'
#   at t/pg.t line 313.
#          got: '@ 0'
#     expected: '@ -1 minutes'

#   Failed test 'parse_interval alt check 4'
#   at t/pg.t line 316.

#   Failed test 'parse_interval (2:)'
#   at t/pg.t line 313.
#          got: '@ 0'
#     expected: '@ 120 minutes'

#   Failed test 'parse_interval alt check 6'
#   at t/pg.t line 316.

#   Failed test 'parse_interval (-1 y 3 h -57 M 4 s)'
#   at t/pg.t line 313.
#          got: '@ -69 months 180 minutes 4 seconds'
#     expected: '@ -12 months 123 minutes 4 seconds'

#   Failed test 'parse_interval alt check 12'
#   at t/pg.t line 316.

#   Failed test 'parse_interval (5 h -208 m -495 s)'
#   at t/pg.t line 313.
#          got: '@ 92 minutes -495 seconds'
#     expected: '@ 83 minutes 45 seconds'

#   Failed test 'parse_interval (-208 m -495 s)'
#   at t/pg.t line 313.
#          got: '@ -208 minutes -495 seconds'
#     expected: '@ -216 minutes -15 seconds'

#   Failed test 'parse_interval (5 h 208 m 495 s)'
#   at t/pg.t line 313.
#          got: '@ 508 minutes 495 seconds'
#     expected: '@ 516 minutes 15 seconds'

#   Failed test 'parse_interval (:)'
#   at t/pg.t line 313.
#          got: '@ 0'
#     expected: undef
Parameter #1 (undef) to DateTime::add_duration was not a 'DateTime::Duration' (it is undef)
 at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime.pm line 1711.
	DateTime::add_duration(undef, undef) called at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime/Duration.pm line 262
	DateTime::Duration::compare("DateTime::Duration", DateTime::Duration=HASH(0x1ce79f8), undef) called at t/pg.t line 316
# Looks like you planned 325 tests but ran 178.
# Looks like you failed 10 tests of 178 run.
# Looks like your test exited with 255 just after 178.
t/pg.t .................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 157/325 subtests 
	(less 15 skipped subtests: 153 okay)
t/pk-columns.t ............ ok
t/pod.t ................... skipped: Test::Pod 1.00 required for testing POD
t/setup.t ................. ok
t/sqlite.t ................ ok
t/storable.t .............. ok
t/subclass-basic.t ........ ok
t/subclass-informix.t ..... skipped: Missing DBD::Informix
t/subclass-list-tables.t .. ok
t/subclass-mysql.t ........ skipped: Missing DBD::mysql
t/subclass-oracle.t ....... skipped: Missing DBD::Oracle

#   Failed test 'parse_interval (-0:1:)'
#   at t/subclass-pg.t line 313.
#          got: '@ 0'
#     expected: '@ -1 minutes'

#   Failed test 'parse_interval alt check 4'
#   at t/subclass-pg.t line 316.

#   Failed test 'parse_interval (2:)'
#   at t/subclass-pg.t line 313.
#          got: '@ 0'
#     expected: '@ 120 minutes'

#   Failed test 'parse_interval alt check 6'
#   at t/subclass-pg.t line 316.

#   Failed test 'parse_interval (-1 y 3 h -57 M 4 s)'
#   at t/subclass-pg.t line 313.
#          got: '@ -69 months 180 minutes 4 seconds'
#     expected: '@ -12 months 123 minutes 4 seconds'

#   Failed test 'parse_interval alt check 12'
#   at t/subclass-pg.t line 316.

#   Failed test 'parse_interval (5 h -208 m -495 s)'
#   at t/subclass-pg.t line 313.
#          got: '@ 92 minutes -495 seconds'
#     expected: '@ 83 minutes 45 seconds'

#   Failed test 'parse_interval (-208 m -495 s)'
#   at t/subclass-pg.t line 313.
#          got: '@ -208 minutes -495 seconds'
#     expected: '@ -216 minutes -15 seconds'

#   Failed test 'parse_interval (5 h 208 m 495 s)'
#   at t/subclass-pg.t line 313.
#          got: '@ 508 minutes 495 seconds'
#     expected: '@ 516 minutes 15 seconds'

#   Failed test 'parse_interval (:)'
#   at t/subclass-pg.t line 313.
#          got: '@ 0'
#     expected: undef
Parameter #1 (undef) to DateTime::add_duration was not a 'DateTime::Duration' (it is undef)
 at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime.pm line 1711.
	DateTime::add_duration(undef, undef) called at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime/Duration.pm line 262
	DateTime::Duration::compare("DateTime::Duration", DateTime::Duration=HASH(0x3836f28), undef) called at t/subclass-pg.t line 316
# Looks like you planned 324 tests but ran 178.
# Looks like you failed 10 tests of 178 run.
# Looks like your test exited with 255 just after 178.
t/subclass-pg.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 156/324 subtests 
	(less 15 skipped subtests: 153 okay)
t/subclass-sqlite.t ....... ok
t/subclass-trx.t .......... ok
t/subclass.t .............. ok
t/trx.t ................... ok

Test Summary Report
-------------------
t/pg.t                  (Wstat: 65280 Tests: 178 Failed: 10)
  Failed tests:  158-161, 166-167, 172, 174, 176, 178
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 325 tests but ran 178.
t/subclass-pg.t         (Wstat: 65280 Tests: 178 Failed: 10)
  Failed tests:  158-161, 166-167, 172, 174, 176, 178
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 324 tests but ran 178.
Files=27, Tests=1265,  4 wallclock secs ( 0.16 usr  0.02 sys +  3.91 cusr  0.30 csys =  4.39 CPU)
Result: FAIL
Failed 2/27 test programs. 20/1265 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing Rose::DB failed. See /home/ubuntu/.cpanm/work/1458335806.26377/build.log for details. Retry with --force to force install it.
```

**Comment by rewolfe** [comment]
Randal, This is something I noticed a while back when trying to build an
instance of GCIS.  There is a problem with the duration library

DateTime::Duration

I think I put a note up when it happened and may have backed off to a prior
version that worked.

On Mon, Mar 21, 2016 at 2:53 PM, rsindlin <notifications@github.com> wrote:

> Below is the full test output with failures during installation via cpanm.
> Pardon me if this is too long; opting for pasting as comment rather than
> attaching as file, for search engines to pick up should anyone else hit
> this issue.
>
> Fetching http://www.cpan.org/authors/id/J/JS/JSIRACUSA/Rose-DB-Object-0.815.tar.gz
> -> OK
> Unpacking Rose-DB-Object-0.815.tar.gz
> Entering Rose-DB-Object-0.815
> Checking configure dependencies from META.json
> Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.98)
> Configuring Rose-DB-Object-0.815
> Running Makefile.PL
> Warning: prerequisite Rose::DB 0.763 not found.
> Checking if your kit is complete...
> Looks good
> Generating a Unix-style Makefile
> Writing Makefile for Rose::DB::Object
> Writing MYMETA.yml and MYMETA.json
> -> OK
> Checking dependencies from MYMETA.json ...
> Checking if you have Math::BigInt 1.77 ... Yes (1.9993)
> Checking if you have Data::Dumper 2.121 ... Yes (2.151)
> Checking if you have Scalar::Util 0 ... Yes (1.38)
> Checking if you have Rose::DateTime::Util 0.532 ... Yes (0.540)
> Checking if you have DBI 1.40 ... Yes (1.634)
> Checking if you have Rose::Object 0.854 ... Yes (0.860)
> Checking if you have List::MoreUtils 0 ... Yes (0.413)
> Checking if you have Time::Clock 1.00 ... Yes (1.03)
> Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.98)
> Checking if you have Test::More 0 ... Yes (1.001014)
> Checking if you have File::Spec 0 ... Yes (3.47)
> Checking if you have File::Path 0 ... Yes (2.09)
> Checking if you have Clone 0.29 ... Yes (0.38)
> Checking if you have Bit::Vector 0 ... Yes (7.4)
> Checking if you have Rose::DB 0.763 ... No
> Checking if you have DateTime 0 ... Yes (1.25)
> Checking if you have Cwd 0 ... Yes (3.47)
> ==> Found dependencies: Rose::DB
> Searching Rose::DB (0.763) on cpanmetadb ...
> --> Working on Rose::DB
> Fetching http://www.cpan.org/authors/id/J/JS/JSIRACUSA/Rose-DB-0.777.tar.gz
> -> OK
> Unpacking Rose-DB-0.777.tar.gz
> Entering Rose-DB-0.777
> Checking configure dependencies from META.json
> Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.98)
> Configuring Rose-DB-0.777
> Running Makefile.PL
> Checking if your kit is complete...
> Looks good
> Generating a Unix-style Makefile
> Writing Makefile for Rose::DB
> Writing MYMETA.yml and MYMETA.json
> -> OK
> Checking dependencies from MYMETA.json ...
> Checking if you have DateTime::Format::Oracle 0 ... Yes (0.06)
> Checking if you have Time::Clock 0 ... Yes (1.03)
> Checking if you have DateTime::Format::MySQL 0 ... Yes (0.06)
> Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.98)
> Checking if you have DateTime::Format::Pg 0.11 ... Yes (0.16011)
> Checking if you have Test::More 0 ... Yes (1.001014)
> Checking if you have Rose::DateTime::Util 0.532 ... Yes (0.540)
> Checking if you have Scalar::Util 0 ... Yes (1.38)
> Checking if you have SQL::ReservedWords 0 ... Yes (0.8)
> Checking if you have DBI 0 ... Yes (1.634)
> Checking if you have Clone::PP 0 ... Yes (1.06)
> Checking if you have Bit::Vector::Overload 6.4 ... Yes (7.4)
> Checking if you have DateTime::Duration 0 ... Yes (1.25)
> Checking if you have Rose::Object 0.854 ... Yes (0.860)
> Building and testing Rose-DB-0.777
> cp lib/Rose/DB.pm blib/lib/Rose/DB.pm
> cp lib/Rose/DB/Oracle.pm blib/lib/Rose/DB/Oracle.pm
> cp lib/Rose/DB/Cache/Entry.pm blib/lib/Rose/DB/Cache/Entry.pm
> cp lib/Rose/DB/Cache.pm blib/lib/Rose/DB/Cache.pm
> cp lib/Rose/DB/Pg.pm blib/lib/Rose/DB/Pg.pm
> cp lib/Rose/DB/Generic.pm blib/lib/Rose/DB/Generic.pm
> cp lib/Rose/DB/MySQL.pm blib/lib/Rose/DB/MySQL.pm
> cp lib/Rose/DB/Registry.pm blib/lib/Rose/DB/Registry.pm
> cp lib/Rose/DB/SQLite.pm blib/lib/Rose/DB/SQLite.pm
> cp lib/Rose/DB/Constants.pm blib/lib/Rose/DB/Constants.pm
> cp lib/Rose/DB/Informix.pm blib/lib/Rose/DB/Informix.pm
> cp lib/Rose/DB/Tutorial.pod blib/lib/Rose/DB/Tutorial.pod
> cp lib/Rose/DB/Registry/Entry.pm blib/lib/Rose/DB/Registry/Entry.pm
> Manifying blib/man3/Rose::DB.3
> Manifying blib/man3/Rose::DB::Cache.3
> Manifying blib/man3/Rose::DB::Cache::Entry.3
> Manifying blib/man3/Rose::DB::Constants.3
> Manifying blib/man3/Rose::DB::Generic.3
> Manifying blib/man3/Rose::DB::Informix.3
> Manifying blib/man3/Rose::DB::MySQL.3
> Manifying blib/man3/Rose::DB::Oracle.3
> Manifying blib/man3/Rose::DB::Pg.3
> Manifying blib/man3/Rose::DB::Registry.3
> Manifying blib/man3/Rose::DB::Registry::Entry.3
> Manifying blib/man3/Rose::DB::SQLite.3
> Manifying blib/man3/Rose::DB::Tutorial.3
> PERL_DL_NONLAZY=1 /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
>
> ##
> ## WARNING: Almost all the tests in this module distribution need to connect
> ## to a database in order to run.  The tests need full privileges on this
> ## database: the ability to create and drop tables, insert, update, and delete
> ## rows, create schemas, sequences, functions, triggers, the works.
> ##
> ## By default, the tests will try to connect to the database named "test"
> ## running on "localhost" using the default superuser username for each
> ## database type and an empty password.
> ##
> ## If you have setup your database in a secure manner, these connection
> ## attempts will fail, and the tests will be skipped.  If you want to override
> ## these values, set the following environment variables before running tests.
> ## (The current values are shown in parentheses.)
> ##
> ## PostgreSQL:
> ##
> ##     RDBO_PG_DSN        (dbi:Pg:dbname=test;host=localhost)
> ##     RDBO_PG_USER       (postgres)
> ##     RDBO_PG_PASS       (<none>)
> ##
> ## MySQL:
> ##
> ##     RDBO_MYSQL_DSN     (dbi:mysql:database=test;host=localhost)
> ##     RDBO_MYSQL_USER    (root)
> ##     RDBO_MYSQL_PASS    (<none>)
> ##
> ## Oracle:
> ##
> ##     RDBO_ORACLE_DSN    (dbi:Oracle:dbname=test)
> ##     RDBO_ORACLE_USER   (<none>)
> ##     RDBO_ORACLE_PASS   (<none>)
> ##
> ## Informix:
> ##
> ##     RDBO_INFORMIX_DSN  (dbi:Informix:test@test)
> ##     RDBO_INFORMIX_USER (<none>)
> ##     RDBO_INFORMIX_PASS (<none>)
> ##
> ## SQLite: To disable the SQLite tests, set this environment varible
> ##
> ##     RDBO_NO_SQLITE (<undef>)
> ##
> ## Press return to continue (or wait 60 seconds)
> t/00-warning.t ............ ok
> t/basic.t ................. ok
> t/db_cache.t .............. ok
> t/fork-informix.t ......... ok
> t/fork-mysql.t ............ ok
> t/fork-pg.t ............... ok
> t/informix.t .............. skipped: Missing DBD::Informix
> t/list-tables.t ........... ok
> t/mysql.t ................. skipped: Missing DBD::mysql
> t/no-registry.t ........... ok
> t/oracle.t ................ skipped: Missing DBD::Oracle
>
> #   Failed test 'parse_interval (-0:1:)'
> #   at t/pg.t line 313.
> #          got: '@ 0'
> #     expected: '@ -1 minutes'
>
> #   Failed test 'parse_interval alt check 4'
> #   at t/pg.t line 316.
>
> #   Failed test 'parse_interval (2:)'
> #   at t/pg.t line 313.
> #          got: '@ 0'
> #     expected: '@ 120 minutes'
>
> #   Failed test 'parse_interval alt check 6'
> #   at t/pg.t line 316.
>
> #   Failed test 'parse_interval (-1 y 3 h -57 M 4 s)'
> #   at t/pg.t line 313.
> #          got: '@ -69 months 180 minutes 4 seconds'
> #     expected: '@ -12 months 123 minutes 4 seconds'
>
> #   Failed test 'parse_interval alt check 12'
> #   at t/pg.t line 316.
>
> #   Failed test 'parse_interval (5 h -208 m -495 s)'
> #   at t/pg.t line 313.
> #          got: '@ 92 minutes -495 seconds'
> #     expected: '@ 83 minutes 45 seconds'
>
> #   Failed test 'parse_interval (-208 m -495 s)'
> #   at t/pg.t line 313.
> #          got: '@ -208 minutes -495 seconds'
> #     expected: '@ -216 minutes -15 seconds'
>
> #   Failed test 'parse_interval (5 h 208 m 495 s)'
> #   at t/pg.t line 313.
> #          got: '@ 508 minutes 495 seconds'
> #     expected: '@ 516 minutes 15 seconds'
>
> #   Failed test 'parse_interval (:)'
> #   at t/pg.t line 313.
> #          got: '@ 0'
> #     expected: undef
> Parameter #1 (undef) to DateTime::add_duration was not a 'DateTime::Duration' (it is undef)
>  at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime.pm line 1711.
>     DateTime::add_duration(undef, undef) called at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime/Duration.pm line 262
>     DateTime::Duration::compare("DateTime::Duration", DateTime::Duration=HASH(0x1ce79f8), undef) called at t/pg.t line 316
> # Looks like you planned 325 tests but ran 178.
> # Looks like you failed 10 tests of 178 run.
> # Looks like your test exited with 255 just after 178.
> t/pg.t ....................
> Dubious, test returned 255 (wstat 65280, 0xff00)
> Failed 157/325 subtests
>     (less 15 skipped subtests: 153 okay)
> t/pk-columns.t ............ ok
> t/pod.t ................... skipped: Test::Pod 1.00 required for testing POD
> t/setup.t ................. ok
> t/sqlite.t ................ ok
> t/storable.t .............. ok
> t/subclass-basic.t ........ ok
> t/subclass-informix.t ..... skipped: Missing DBD::Informix
> t/subclass-list-tables.t .. ok
> t/subclass-mysql.t ........ skipped: Missing DBD::mysql
> t/subclass-oracle.t ....... skipped: Missing DBD::Oracle
>
> #   Failed test 'parse_interval (-0:1:)'
> #   at t/subclass-pg.t line 313.
> #          got: '@ 0'
> #     expected: '@ -1 minutes'
>
> #   Failed test 'parse_interval alt check 4'
> #   at t/subclass-pg.t line 316.
>
> #   Failed test 'parse_interval (2:)'
> #   at t/subclass-pg.t line 313.
> #          got: '@ 0'
> #     expected: '@ 120 minutes'
>
> #   Failed test 'parse_interval alt check 6'
> #   at t/subclass-pg.t line 316.
>
> #   Failed test 'parse_interval (-1 y 3 h -57 M 4 s)'
> #   at t/subclass-pg.t line 313.
> #          got: '@ -69 months 180 minutes 4 seconds'
> #     expected: '@ -12 months 123 minutes 4 seconds'
>
> #   Failed test 'parse_interval alt check 12'
> #   at t/subclass-pg.t line 316.
>
> #   Failed test 'parse_interval (5 h -208 m -495 s)'
> #   at t/subclass-pg.t line 313.
> #          got: '@ 92 minutes -495 seconds'
> #     expected: '@ 83 minutes 45 seconds'
>
> #   Failed test 'parse_interval (-208 m -495 s)'
> #   at t/subclass-pg.t line 313.
> #          got: '@ -208 minutes -495 seconds'
> #     expected: '@ -216 minutes -15 seconds'
>
> #   Failed test 'parse_interval (5 h 208 m 495 s)'
> #   at t/subclass-pg.t line 313.
> #          got: '@ 508 minutes 495 seconds'
> #     expected: '@ 516 minutes 15 seconds'
>
> #   Failed test 'parse_interval (:)'
> #   at t/subclass-pg.t line 313.
> #          got: '@ 0'
> #     expected: undef
> Parameter #1 (undef) to DateTime::add_duration was not a 'DateTime::Duration' (it is undef)
>  at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime.pm line 1711.
>     DateTime::add_duration(undef, undef) called at /home/ubuntu/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.0/x86_64-linux/DateTime/Duration.pm line 262
>     DateTime::Duration::compare("DateTime::Duration", DateTime::Duration=HASH(0x3836f28), undef) called at t/subclass-pg.t line 316
> # Looks like you planned 324 tests but ran 178.
> # Looks like you failed 10 tests of 178 run.
> # Looks like your test exited with 255 just after 178.
> t/subclass-pg.t ...........
> Dubious, test returned 255 (wstat 65280, 0xff00)
> Failed 156/324 subtests
>     (less 15 skipped subtests: 153 okay)
> t/subclass-sqlite.t ....... ok
> t/subclass-trx.t .......... ok
> t/subclass.t .............. ok
> t/trx.t ................... ok
>
> Test Summary Report
> -------------------
> t/pg.t                  (Wstat: 65280 Tests: 178 Failed: 10)
>   Failed tests:  158-161, 166-167, 172, 174, 176, 178
>   Non-zero exit status: 255
>   Parse errors: Bad plan.  You planned 325 tests but ran 178.
> t/subclass-pg.t         (Wstat: 65280 Tests: 178 Failed: 10)
>   Failed tests:  158-161, 166-167, 172, 174, 176, 178
>   Non-zero exit status: 255
>   Parse errors: Bad plan.  You planned 324 tests but ran 178.
> Files=27, Tests=1265,  4 wallclock secs ( 0.16 usr  0.02 sys +  3.91 cusr  0.30 csys =  4.39 CPU)
> Result: FAIL
> Failed 2/27 test programs. 20/1265 subtests failed.
> make: *** [test_dynamic] Error 255
> -> FAIL Installing Rose::DB failed. See /home/ubuntu/.cpanm/work/1458335806.26377/build.log for details. Retry with --force to force install it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/siracusa/rose/issues/9#issuecomment-199423533>
>



-- 
Robert Wolfe, NASA GSFC @ USGCRP, o: 202-419-3470, m: 301-257-6966

**Comment by siracusa** [comment]
I've updated the tests to work with (and require) the latest version of DateTime::Format::Pg.
